### ISSUE TITLE
17.3.1 not available on Docker Hub

### ISSUE THREAD

**Issue by mdartmann** [zengxs/gitlab-arm64#122]
Hi,

thank you for your work, this image is really useful. 

Unfortunately, it seems like version 17.3.1 didn’t make it onto Docker Hub, even though the CI pipeline finished successfully: 

https://github.com/zengxs/gitlab-arm64/actions/runs/10501936314/job/29092730299?pr=121

Could you please investigate this? Thank you!

**Comment by zengxs** [comment]
Hi,

I apologize for the delayed response; I've been quite busy recently.

The CI pipeline that updates the version number runs automatically, but pushing to Docker Hub requires a manual merge into the main branch. This step is necessary to prevent errors from automatic updates and to verify if there have been any changes to the upstream Dockerfile.

The version should now be available on Docker Hub.

Thank you for your understanding!

**Comment by mdartmann** [comment]
Hi!
Thank you so much for the fix, and for maintaining this image in general! Can confirm it’s available!
