### ISSUE TITLE
Please update versions

### ISSUE THREAD

**Issue by Giattuck** [zengxs/gitlab-arm64#132]
Greetings, 
Thank you for this wonderful project!

However, I have noticed that recently updating versions has been a bit slow, for example at the moment we are 2 versions behind (17.3.3 - 17.4.0).

Is it possible to have the update a little earlier, or a tutorial on how to do it independently?

Thanks again!

**Comment by zengxs** [comment]
Hi,

Thank you for your kind words and for bringing this to my attention.

I apologize for the recent delays in updating the project versions, as I've been quite busy over the past few months. I'll do my best to keep the updates more timely moving forward.

In the meantime, if you wish to manually update, please refer to the **Building the Image Yourself** section in the README for guidance.

Thank you for your understanding!
