### ISSUE TITLE
Add a "buy me a coffee" button on this repo.

### ISSUE THREAD

**Issue by sjacobflaherty** [zengxs/gitlab-arm64#145]
So that I can buy you a coffee for saving me 20 hours of build research. It'd be great if you could maintain this image until Gitlab gets their butts in gear! Until then, please allow me to show my appreciation. :)

**Comment by zengxs** [comment]
Thank you so much for your kind words! I'm really glad to hear that this saved you so much time. Your appreciation is more than enough for me — knowing the project is helpful to others is what motivates me. I'll do my best to keep this maintained until GitLab improves their support. Thanks again for your encouragement! 😊
