### ISSUE TITLE
关于更低版本的 GitLab 镜像制作问题

### ISSUE THREAD

**Issue by zhenzhenChange** [zengxs/gitlab-arm64#28]
hub 主你好，非常感谢你的付出。

有个问题我想请教一下，对于更低的版本来说，官方是不是没有支持 ARM 架构了呢？

<img width="1265" alt="图片" src="https://github.com/zengxs/gitlab-arm64/assets/51586637/6054774a-ba4b-44c6-8088-5617826f55a3">

比如我是 M2 的 MacBook Pro，其实想复刻一下我司的 GitLab 环境验证一些问题，不过貌似这个版本是不支持的：

<img width="1794" alt="图片" src="https://github.com/zengxs/gitlab-arm64/assets/51586637/3c43107a-64d7-484b-baf7-79f03a33b0ee">

其它比较高的版本倒是没问题。

<img width="1376" alt="图片" src="https://github.com/zengxs/gitlab-arm64/assets/51586637/6f602596-64b3-4c02-98db-49cdf315dd2a">

我想问，如果官方没有支持，还有什么办法能够构建更低的版本镜像使其在 ARM 架构上运行吗？

**Comment by zengxs** [comment]
GitLab 的 ARM 64 应该是 13.4 才开始有的，官方没有提供的版本很难打出来镜像

如果是单纯为了验证某个版本的问题，可以考虑使用 Rosetta 2 运行 x86-64 版本的 Docker 镜像

**Comment by zengxs** [comment]
GitLab 的 ARM 64 应该是 13.4 才开始有的，官方没有提供的版本很难打出来镜像

如果是单纯为了验证某个版本的问题，可以考虑使用 Rosetta 2 运行 x86-64 版本的 Docker 镜像

**Comment by zhenzhenChange** [comment]
明白了，非常感谢
