### ISSUE TITLE
Editions explanation not quite right (for self-hosted instances)

### ISSUE THREAD

**Issue by IT-VBFK** [zengxs/gitlab-arm64#37]
Hi

> CE represents the community edition, which is open source and free. EE represents the enterprise edition, which includes more features but requires a license purchased from [GitLab B.V.](https://about.gitlab.com/pricing/).

The description about GitLab CE/EE is not quite correct. The actual difference is that (if you self-host you instance) you only be able to upgrade to a paid tier if you are on EE but not CE.

**Comment by zengxs** [comment]
Thank you for bringing the error in editions explanation to my attention.
I appreciate your help in pointing it out. I have now corrected the description.
